default: &default
  adapter: postgresql
  encoding: unicode
  username: oana
  pool: 5

development:
  <<: *default
  database: care2share_dev
test:
  <<: *default
  database: care2share_test
production:
  <<: *default
  database: care2share_prod
  password: <%= ENV['CARE2SHARE_DATABASE_PASSWORD'] %>
